site_name: FRAM demo
site_author: NVE
site_description: >-
  FRAM demo documentation site

repo_url: https://github.com/NVE/fram-demo
repo_name: NVE/fram-demo

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github    

nav:
  - index.md
  - demo_description.md

  # - Code Reference:
  #   - reference/EventHandler.md
  #   - reference/dashboard_app.md
  #   - reference/demo_utils.md

markdown_extensions:
- tables
- attr_list

plugins:
  - mkdocstrings:
     handlers:
        python:
          options:  
            show_submodules: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
  - mike
  - search
  - macros
  - table-reader

extra:
  version:
    provider: mike
  framlinks:
    nve: https://www.nve.no/english/
    fram: https://nve.github.io/fram/
    dataset: https://zenodo.org/records/17294467
    jules: https://github.com/NVE/JulES/
    julia: https://julialang.org/

extra_css:
  - assets/styles.css